# Generated by Django 2.1.7 on 2019-03-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.CharField(choices=[('GA', 'Global Admin'), ('ADM', 'Admin')], default='ADM', max_length=3)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('password_expire', models.BooleanField(default=False)),
                ('password_expire_date', models.DateTimeField(auto_now_add=True)),
                ('token_generated', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('can_edit', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
